name: QA

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  qa:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check banned punctuation
        run: python3 scripts/check_banned_chars.py .

      - name: Markdown lint
        uses: avto-dev/markdown-lint@v1.5.0
        with:
          config: .markdownlint.yml

      - name: Link check
        uses: lycheeverse/lychee-action@v1.10.0
        with:
          args: --verbose --no-progress --exclude-mail --accept 200,429,999 .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
