name: Generate Resume from JD

on:
  push:
    paths:
      - 'runs/**/inputs/jd.md'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Generate Resume(s)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "[DEBUG] Scanning for jd.md files..."
          find runs -type f -path "*/inputs/jd.md" | while read jd; do
            echo "[DEBUG] Processing JD: $jd"
            python scripts/generate_resume_from_jd.py "$jd"
          done

      - name: Upload resume artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resumes
          path: runs/**/outputs/*

      - name: Commit Outputs
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions"
          git add runs/**/outputs/* || true
          git commit -m "Add generated resumes" || echo "[DEBUG] No new resumes to commit"
          git push || echo "[DEBUG] Nothing new to push"

      - name: Update Google Sheet
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: |
          echo "[DEBUG] Updating Google Sheet..."
          find runs -type f -path "*/outputs/result.json" | while read result; do
            python scripts/update_sheet.py "$result"
          done
