name: Generate Resume from JD

on:
  push:
    paths:
      - 'runs/**/inputs/jd.md'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - run: |
          pip install python-docx google-auth google-auth-httplib2 google-api-python-client pyyaml

      - name: Generate Resume
        run: |
          find runs -type f -path "*/inputs/jd.md" | while read jd; do
            echo "Processing $jd"
            python scripts/generate_resume_from_jd.py "$jd" > result.json
          done

      - name: Upload resume artifacts
        uses: actions/upload-artifact@v3
        with:
          name: resumes
          path: runs/**/outputs/*.docx

      - name: Commit Outputs
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions"
          git add runs/**/outputs/*.docx || true
          git commit -m "Add generated resumes" || echo "No changes"
          git push

      - name: Update Google Sheet
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: |
          python scripts/update_sheet.py result.json
