name: Generate Resume from JD

on:
  push:
    paths:
      - 'runs/**/inputs/jd.md'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Check for resume template
        run: |
          if [ ! -f "templates/resume_template.docx" ]; then
            echo "[ERROR] Missing templates/resume_template.docx"
            exit 1
          fi

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install python-docx google-auth google-auth-httplib2 google-api-python-client pyyaml openai

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Generate Resume(s)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "[DEBUG] Scanning for jd.md files..."
          find runs -type f -path "*/inputs/jd.md" | while read jd; do
            echo "[DEBUG] Processing JD: $jd"
            python scripts/generate_resume_from_jd.py "$jd"
          done

      - name: Run banned character check (outputs only)
        run: python scripts/check_banned_chars.py runs/**/outputs

      - name: Debug outputs directory
        run: |
          echo "[DEBUG] Listing outputs folder contents:"
          ls -R runs || true

      - name: Upload resume artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resumes
          path: runs/**/outputs/*.docx

      - name: List generated resume files
        run: |
          echo "[INFO] Generated resumes:"
          ls -lh runs/**/outputs/*.docx || echo "[WARN] No resumes found"

      - name: Commit Outputs
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions"
          git add runs/**/outputs/*.docx runs/**/outputs/result.json || true
          git commit -m "Add generated resumes" || echo "[DEBUG] No new resumes to commit"
          git push || echo "[DEBUG] Nothing new to push"

      - name: Update Google Sheet
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: |
          echo "[DEBUG] Looking for result.json..."
          RESULT_FILE=$(find runs -type f -name "result.json" | sort | tail -n 1)
          if [ -z "$RESULT_FILE" ]; then
            echo "[ERROR] No result.json found!"
            exit 1
          fi
          echo "[DEBUG] Using result.json at: $RESULT_FILE"
          python scripts/update_sheet.py "$RESULT_FILE"

      - name: Debug env vars
        run: |
          echo "GOOGLE_SHEETS_CREDENTIALS length: ${#GOOGLE_SHEETS_CREDENTIALS}"
          echo "SHEET_ID: $SHEET_ID"
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
