name: Resume Generator (Claude)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  resume:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies (force clean Anthropic)
        run: |
          python -m pip install --upgrade pip
          # force reinstall Anthropic cleanly to avoid proxies bug
          pip install anthropic==0.39.0 --force-reinstall --no-cache-dir
          # then install the rest of your project dependencies
          pip install -r requirements.txt

      - name: Verify Anthropic version
        run: |
          python -c "import anthropic; print('Anthropic version:', anthropic.__version__); print('Loaded from:', anthropic.__file__)"

      - name: Run resume generation
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          echo "🔍 Running resume generator with Claude..."
          python scripts/generate_resume_from_jd.py runs/sample/jd.md
