name: Resume Generator (Claude)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  resume:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install anthropic==0.39.0

      - name: Run resume generation
        env:
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
        run: |
          echo "🔍 Running resume generator with Claude..."
          python scripts/generate_resume_from_jd.py runs/sample/jd.md
