name: Resume Generator (OpenAI REST)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  resume:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Verify requests version
        run: |
          python -c "import requests; print('Requests version:', requests.__version__); print('Loaded from:', requests.__file__)"

      - name: Run resume generation
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "🔍 Running resume generator with OpenAI REST API..."
          python scripts/generate_resume_from_jd.py runs/sample/jd.md

      - name: Upload resume outputs
        uses: actions/upload-artifact@v4
        with:
          name: resumes
          path: runs/outputs/
