name: Generate Resume from JD

on:
  push:
    paths:
      - 'runs/**/inputs/jd.md'
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate Resume(s)
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "[DEBUG] Scanning for jd.md files..."
          found=0
          for jd in $(find runs -type f -path "*/inputs/jd.md"); do
            found=1
            echo "[DEBUG] Processing JD: $jd"
            python scripts/generate_resume_from_jd.py "$jd"
          done
          if [ $found -eq 0 ]; then
            echo "[WARN] No jd.md files found under runs/**/inputs/"
            exit 0
          fi

      - name: Debug outputs directory
        run: |
          echo "[DEBUG] Listing outputs folder contents:"
          ls -R runs || true

      - name: Upload resume artifacts
        uses: actions/upload-artifact@v4
        with:
          name: resumes
          path: runs/**/outputs/*

      - name: Commit Outputs
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "github-actions"
          git add runs/**/outputs/* || true
          git commit -m "Add generated resumes" || echo "[DEBUG] No new resumes to commit"
          git push || echo "[DEBUG] Nothing new to push"

      - name: Update Google Sheet
        if: success()   # 👈 ensures Sheets only runs if resume generation succeeded
        env:
          GOOGLE_SHEETS_CREDENTIALS: ${{ secrets.GOOGLE_SHEETS_CREDENTIALS }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
        run: |
          echo "[DEBUG] Updating Google Sheet..."
          for result in $(find runs -type f -path "*/outputs/result.json"); do
            echo "[DEBUG] Sending $result"
            python scripts/update_sheet.py "$result"
          done
